version: '3.8'

services:
  cineps-app:
    image: angular:2.5
    build:
      context: ./docker/
      dockerfile: Dockerfile-Node
    container_name: cineps-app
    deploy:
      resources:
        limits:
          cpus: '8.0'
    ports:
      - 5001:5000
      - 4916:49153
    volumes:
      - ./front:/usr/src/app

 